### ISSUE TITLE
Issue With Google

### ISSUE THREAD

**Issue by perfectpitchconcepts** [pulkitjalan/google-apiclient#11]
Just tried running "composer require pulkitjalan/google-apiclient" and got the following error:

  Problem 1
    - pulkitjalan/google-apiclient 2.0.1 requires google/apiclient 1.* -> no matching package found.
    - pulkitjalan/google-apiclient 2.0 requires google/apiclient 1.* -> no matching package found.
    - Installation request for pulkitjalan/google-apiclient ^2.0 -> satisfiable by pulkitjalan/google-apiclient[2.0, 2.0.1].

Looks like the google/apiclient package recently updated their version number. Assuming that's the issue here? 

Thanks! Looking forward to getting your wrapped installed and playing around with it a bit!

**Comment by pulkitjalan** [comment]
Version 3 fixes this.
