### ISSUE TITLE
Path to .json file

### ISSUE THREAD

**Issue by KriiV** [pulkitjalan/google-apiclient#16]
I'm struggling to understand the correct way to write the path to the service account .json file.

Help would be appreciated.

**Comment by iggori** [comment]
'file' => env('GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION', base_path('some_folder/some_name.json'))

**Comment by pulkitjalan** [comment]
Thanks @iggori. 

@KriiV it needs to be the full path to the file. If you are using the environment variable in you .env then you can simply set it like so:

GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION=/full/path/to/json/file

As an alternative you can modify the config file as show by @iggori above.
