### ISSUE TITLE
Not Authorized to access this resource/api

### ISSUE THREAD

**Issue by fofaraz** [pulkitjalan/google-apiclient#21]
I'm getting this error when using directory SDK
it seems like i need to set sub somehow
i know that i can set sub Google::getClient() with a second parameter
but how can i set sub when i need to get a service?

$directory = Google::make('directory');

is there any way to set sub in above command?

**Comment by pulkitjalan** [comment]
Hmm, unless you can do

```php
$directory = Google::make('directory');
$directory->setSub();
```

i dont think it will be possible, it might be good to be able to set the client back so you could do something like:

```php
$client = Google::getClient();
$client->setSub();
Google::setClient($client);

$directory = Google::make('directory');
```

**Comment by victorlap** [comment]
Is there a way to include this in the config?

**Comment by pulkitjalan** [comment]
No sorry, unless it's something that the Google sdk it self supports being passed in via the config, there is no way.

**Comment by victorlap** [comment]
The Google Sdk supports it by default, see https://github.com/google/google-api-php-client/blob/master/src/Google/Client.php#L119

**Comment by pulkitjalan** [comment]
Cool, ive just tagged a new release adding support for passing config through to the Google Client.

https://github.com/pulkitjalan/google-apiclient/commit/36a34840aeda19ba6f0e437483f795e937a35de2

You should be able to set the subject in the config using:

```php
config => [
    'subject' => '...'
],
```

**Comment by victorlap** [comment]
Great! Thanks a lot!
