### ISSUE TITLE
Getting Gmail Access

### ISSUE THREAD

**Issue by sbasi5576** [pulkitjalan/google-apiclient#22]
I am looking to be able to read a user's email in the gmail.  Basically watch for any updates in the inbox matching a string e.g. Stock Alerts .  I can I use this client?  If yes, can you please document an example.

**Comment by pulkitjalan** [comment]
Hey,

Sorry im not really sure, this is a thin wrapper around googles own api client. I mostly use it for authentication and then easily getting google own api client classes.

If that's something googles api client offers then you should be able to use this to get the relevant class and use it directly.
