### ISSUE TITLE
Authorization prompt is not poping up

### ISSUE THREAD

**Issue by shakee93** [pulkitjalan/google-apiclient#23]
![image](https://cloud.githubusercontent.com/assets/14835725/25894595/0dd507e4-359a-11e7-9d6c-910344ec0b4f.png)
above is the error i am getting.. why am i not getting the auth popup ? what am i doing wrong in here can you please explain ?

this is how i am making the request
```php
$youtube = \Google::make('youtube');

        $youtube->channels->listChannels(
            'id,contentDetails',
            [
                'mine' => true
            ]
        );
```

this is the config

```php
'client_id'       => env('GOOGLE_CLIENT_ID', ''),
    'client_secret'   => env('GOOGLE_CLIENT_SECRET', ''),
    'redirect_uri'    => env('GOOGLE_REDIRECT', ''),
    'scopes'          => [
        'https://www.googleapis.com/auth/yt-analytics.readonly',
        'https://www.googleapis.com/auth/yt-analytics-monetary.readonly',
        'https://www.googleapis.com/auth/youtube',
        'https://www.googleapis.com/auth/youtubepartner',
    ],
    'access_type'     => 'online',
    'approval_prompt' => 'auto',
```
Thank you !!

**Comment by LukeTowers** [comment]
@shakee93 what was your solution?

**Comment by shakee93** [comment]
this doc helped me : https://developers.google.com/api-client-library/php/auth/web-app

below method will return google auth url.

```php 
\Google::getClient()->createAuthUrl() 
```
when user allows it will redirect to the redirect url with auth code.

```php
\Google::getClient()->authenticate($auth_code);
```
pass the user given auth token to `authenticate` method and it will return the access/refresh token.

**Comment by carpad88** [comment]
@shakee93 how do you get the `$auth_code` on the redirected url?
