### ISSUE TITLE
File does not exist

### ISSUE THREAD

**Issue by tolborg** [pulkitjalan/google-apiclient#28]
I can't get my head around what I'm doing wrong here. I'm trying to connect using Service Account. 

GOOGLE_APPLICATION_NAME=
GOOGLE_CLIENT_ID=
GOOGLE_CLIENT_SECRET=
GOOGLE_REDIRECT=
GOOGLE_DEVELOPER_KEY=
GOOGLE_SERVICE_ENABLED=true
GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION=/resources/google/service-account.json

I get the error:
InvalidArgumentException 
file does not exist

What am I doing wrong?
(I have tried different variations of the path)

**Comment by pulkitjalan** [comment]
The path has to be an absolute path to the file on your server. So from your description, you file is in 

/resources/... 

And not 

app_path()./resources/...

If it's in app path then resources, u will need to alter the config file.

**Comment by tolborg** [comment]
Yes. I ended up doing this in google.php config file:

'file' => base_path() . '/' . env('GOOGLE_SERVICE_ACCOUNT_JSON_LOCATION', '')
