### ISSUE TITLE
How to fetch data with private google sheet ?

### ISSUE THREAD

**Issue by sunh-2087** [pulkitjalan/google-apiclient#43]
Call google sheet and error
```
   Google_Service_Exception  : {
  "error": {
    "code": 403,
    "message": "The caller does not have permission",
    "errors": [
      {
        "message": "The caller does not have permission",
        "domain": "global",
        "reason": "forbidden"
      }
    ],
    "status": "PERMISSION_DENIED"
  }
}
```

**Comment by teenugrg** [comment]
you can use google sheet api to fetch the data from any google sheet , i am attaching a repo where it help s app which polls a google spreadsheet and generates JSON or JS files used as translation keys

link:ddresch/meteor-i18n-monitor 181

For the authentication setup check this one:
link: https://github.com/reactioncommerce/meteor-google-spreadsheets

**Comment by Peterragheb** [comment]
@sunh-2087 Have you been able to fix this?
