### ISSUE TITLE
trouble accessing Gmail Service

### ISSUE THREAD

**Issue by devinfd** [pulkitjalan/google-apiclient#5]
I keep getting the following error:
```php
Error calling GET https://www.googleapis.com/gmail/v1/users/me/messages: (400) Bad Request
```
with the following code:
```php
$gmail = \Google::make('gmail');
$results = $gmail->users_messages->listUsersMessages('me');
```

As far as I can tell I have set up the credentials correctly yet, its not working. Any advise?

**Comment by pulkitjalan** [comment]
What type of exception is thrown?

Can you put a try catch around the result and DD the response, there should
be a getResponse` or similar in the exception.

Usually the response would contain the reason for the error.

**Comment by devinfd** [comment]
The exception is `\Google_Service_Exception` and its getErrors method returns this
```php
array:1 [
  0 => array:3 [
    "domain" => "global"
    "reason" => "failedPrecondition"
    "message" => "Bad Request"
  ]
]
```

**Comment by pulkitjalan** [comment]
Are you using service account credentials or oauth2?

**Comment by devinfd** [comment]
Service

- Devin Dombrowski

**Comment by pulkitjalan** [comment]
Looks like when using a service account, you need to be able to set `sub`, which you currently cant with this wrapper. Once you can set `sub` you need to make sure you enable the correct api security settings: http://stackoverflow.com/questions/24946453/google-api-oauth2-service-account-error-invalid-grant. Also looks like a `service account` can't be used for personal accounts, if I have understood it correctly.

Ill look into a way of setting `sub` for the request.

**Comment by devinfd** [comment]
You lost me with the `Sub` thing. Not sure what that is. Also fyi, this is for a business account and I did set the security settings from the Google Apps Admin Console but Im not convinced thats helpful because those settings are for Oauth1. What ever you are able to figure out, I really appreciate it.

Devin Dombrowski
dddesigns3@gmail.com

**Comment by pulkitjalan** [comment]
Sorry, yea `sub` would be set to the `email address` of the user you are trying to imitate.

Ill have a look over the weekend anyway.

**Comment by avanderbergh** [comment]
Hi, have you found a way to set  the sub for the Service Account yet? I also desperately need this for use with Google Drive Service.

**Comment by avanderbergh** [comment]
Hi... I have implemented the ability to sub a user please check out my pull request.

**Comment by pulkitjalan** [comment]
Merged, like II mentioned in the pull request, it needs a bit more work for laravel, so might change
