### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by kriiv** [pulkitjalan/google-apiclient#51]
Hey,
Looking to install this on Laravel 8 however no support yet. Would it be as simple as a pull request bumping the dependency number?
I wish a knew a little more to help out.

**Comment by calebanthony** [comment]
This upgrade _should_ just be a version bump, based on what I can see in the source code. There weren't any changes to service providers in 8.x.

**Comment by nekromoff** [comment]
Indeed. Please update, so we can update!

**Comment by nekromoff** [comment]
@pulkitjalan

**Comment by pulkitjalan** [comment]
Merged, Thanks!
