### ISSUE TITLE
PHP 8.0

### ISSUE THREAD

**Issue by Bluefitdev** [pulkitjalan/google-apiclient#55]
Any plan to support php 8? 

Thanks!

**Comment by bickle66** [comment]
That would be great for me too.

Thanks,

**Comment by RipleWare** [comment]
Me three....

**Comment by afrazahmmad** [comment]
Looking for php 8 support!

**Comment by aroy314** [comment]
please @pulkitjalan could you release a new tag for PHP 8 support ? thanks

**Comment by aknEvrnky** [comment]
I got problems on php version at 8.0.15. Can you update it to php 8.1 so I can use any of them.
