### ISSUE TITLE
Require illuminate/support

### ISSUE THREAD

**Issue by nam-co** [pulkitjalan/google-apiclient#56]
Hello, hope somebody can help me, Im trying to install. the package in "laravel/framework": "^8.40", but Im getting this error
 
Problem 1
pulkitjalan/google-apiclient[3.1.0, ..., 3.1.4] require illuminate/support ~5 -> found illuminate/support[v5.0.0, ..., 5.8.x-dev] but these were not loaded, likely because it conflicts with another require.

Root composer.json requires pulkitjalan/google-apiclient ^3.1 -> satisfiable by pulkitjalan/google-apiclient[3.1.0, ..., 3.1.4].

**Comment by bigzooooz** [comment]
i have the same issue

**Comment by devsquad-samuel-franca** [comment]
me too

**Comment by jorgealvz** [comment]
I had to added the dependency manually in composer.json file this was the only thing that works for me
`"pulkitjalan/google-apiclient": "^4.1.1"`
For some reason composer require pulkitjalan/google-apiclient seems to be loading an older version of the library and not the last one
