### ISSUE TITLE
Getting issue while creating auth url

### ISSUE THREAD

**Issue by anil1712** [pulkitjalan/google-apiclient#6]
I am getting following error:

FatalErrorException in Client.php line 267:
Call to undefined method Google_Auth_ComputeEngine::createAuthUrl()

Please give me some solution for this.

**Comment by Dreanmer** [comment]
hey, u can comment out line 44 from `vendor/pulkitjalan/google-apiclient/src/Client.php` this will temp fix the problem.

**Comment by pulkitjalan** [comment]
You can now disable service accounts in the config. Disabling it should fix this issue.

**Comment by Dreanmer** [comment]
Can you release it as an minor version?

**Comment by pulkitjalan** [comment]
done

**Comment by Dreanmer** [comment]
nice! thanks
