### ISSUE TITLE
Not Compatible with laravel 9

### ISSUE THREAD

**Issue by moathOSA** [pulkitjalan/google-apiclient#60]
Problem 1
    - Root composer.json requires pulkitjalan/google-apiclient ^5.0 -> satisfiable by pulkitjalan/google-apiclient[5.0.0].
    - pulkitjalan/google-apiclient 5.0.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
  Problem 2
    - pulkitjalan/google-apiclient 5.0.0 requires illuminate/support ^6.0|^7.0|^8.0 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev, v8.0.0, ..., 8.x-dev] but it conflicts with your root composer.json require (^9.0).
    - revolution/laravel-google-sheets 5.8.0 requires pulkitjalan/google-apiclient ^4.1||^5.0 -> satisfiable by pulkitjalan/google-apiclient[5.0.0].
    - Root composer.json requires revolution/laravel-google-sheets ^5.8 -> satisfiable by revolution/laravel-google-sheets[5.8.0].

**Comment by dmitryvasilevskiy** [comment]
+

**Comment by Nuvm** [comment]
Fixed in #58
