### ISSUE TITLE
Google Sheets API now uses underscores instead of backslash which causes the package to throw UnknownServiceException error

### ISSUE THREAD

**Issue by Xsert** [pulkitjalan/google-apiclient#66]
Google Sheets API now uses underscores instead of backslash which causes the package to throw UnknownServiceException error

https://developers.google.com/sheets/api/guides/values#write_multiple_ranges
![image](https://github.com/pulkitjalan/google-apiclient/assets/8445427/f2f7cdfb-e630-426b-86a6-2d733d8322e6)

vendor\pulkitjalan\google-apiclient\src\Client.php

```
/**
     * Getter for the google service.
     *
     * @param  string  $service
     * @return \Google_Service
     *
     * @throws \Exception
     */
    public function make($service)
    {
        $service = 'Google\\Service\\'.ucfirst($service);

        if (class_exists($service)) {
            $class = new \ReflectionClass($service);

            return $class->newInstance($this->client);
        }

        throw new UnknownServiceException($service);
    }
```

**Comment by pulkitjalan** [comment]
Looks resolved now.
<img width="592" alt="Screenshot 2024-06-30 at 21 50 42" src="https://github.com/pulkitjalan/google-apiclient/assets/4124930/5f86c7db-6829-43af-9218-752b6864c2b7">
